
#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = 16777215
	chance = 1.0
	growthFactor = 0
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = 16776960
	chance = 0.05
	growthFactor = 1
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = 6750207
	chance = 0.04
	growthFactor = 4
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = 13382655
	chance = 0.025
	growthFactor = 9
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = 16750848
	chance = 0.01
	growthFactor = 16
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 5
	numAffixes = 5
	defaultColor = 65280
	chance = 0.005
	growthFactor = 25
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 6
	numAffixes = 6
	defaultColor = 16711680
	chance = 0.002
	growthFactor = 35
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 7
	numAffixes = 5
	defaultColor = 16381148
	chance = 0.0
	growthFactor = 100
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 8
	numAffixes = 8
	defaultColor = 1005988
	chance = 0.0
	growthFactor = 50
	effects = []
	presetAffixes = []

[[ranks]]
	tier = 9
	numAffixes = 8
	defaultColor = 13434624
	chance = 0.0
	growthFactor = 100
	effects = []
	presetAffixes = []

